[package]
name = "roids"
version = "0.1.0"
edition = "2024"

[features]
watcher = [
  "bevy/file_watcher",
  "bevy/embedded_watcher",
]

[dependencies]
bevy = { version = "0.17.2", features = [
    "bevy_asset",
] }
rand = "0.9.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
bevy_common_assets= {version = "0.14.0", features = ["json"]}
serde = "1"
serde_json = "1"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "1.18.1", default-features = false, features = ["js"] }
